image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo 'init script'
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip wheel setuptools
      pip install -e .
      pip install -r requirements.txt
    command: |
      echo 'start script'
      source .venv/bin/activate
      python examples/quickstart.py

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - donjayamanne.githistory

github:
  prebuilds:
    branches: true