image: gitpod/workspace-python-3.9:2022-07-26-05-11-39

tasks:
  - init: |
      echo 'init script'
      python -m pip install --upgrade pip wheel setuptools
      pip install -e .
      pip install -r requirements.txt
    command: |
      echo 'start script'
      cd examples
      python quickstart.py

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - donjayamanne.githistory

github:
  prebuilds:
    branches: true
