[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# addopts = "-p no:warnings"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::pytorch_lightning.utilities.warnings.LightningDeprecationWarning",
    # "ignore::UserWarning",
]
testpaths = ["tests"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
